import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/providers/next-auth-provider";
import { auth } from "@/services/next-auth/auth";
import ReduxProvider from "@/components/providers/redux-provider";
import { ModalProvider } from "@/components/providers/modal-provider";
import { ModalContextProvider } from "@/hooks/customs/use-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <ReduxProvider>
            <ModalContextProvider>
              <ModalProvider />
              {children}
            </ModalContextProvider>
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
