import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/providers/redux-provider";
import NextAuthProvider from "@/components/providers/next-auth-provider";
import { auth } from "@/services/next-auth/auth";
import { SocketProvider } from "@/hooks/context/use-socket-context";
import { ModalContextProvider } from "@/hooks/context/use-modal-context";
import QueryProvider from "@/components/providers/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <QueryProvider>
          <ReduxProvider>
            <ModalContextProvider>
              <SocketProvider isAuthenticated={!!session?.user}>
                {children}
              </SocketProvider>
            </ModalContextProvider>
          </ReduxProvider>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
